### ISSUE TITLE
Apply ks2 to all studies where it can run

### ISSUE THREAD

**Issue by magland** [flatironinstitute/spikeforest_old#20]
I think this means everything that does not have tetrode

**Comment by alexmorley** [comment]
Just FYI I have it working on tetrodes :)

**Comment by magland** [comment]
@jamesjun , we should synchronize our kilosort2 with @alexmorley 's version. Alex, do you have a pull request for it?

**Comment by alexmorley** [comment]
It's at #17 . The only tricky thing is that the fix involves a few small changes to kilosort itself. (But it also works without those changes, just not on tetrodes).

**Comment by magland** [comment]
Great! James and I will take a look next week.

**Comment by jamesjun** [comment]
I confirmed that Alex's fix for Kilosort2 works on testrodes, 8-trode, and
neuropix32c channels with reasonable accuracy scores. I will point to this
Kilosort2 version for the spike sorting validation purpose.

-James

**Comment by magland** [comment]
spikeforest is now pointing to morley's version and everything is re-running
