### ISSUE TITLE
Add wave_clus

### ISSUE THREAD

**Issue by alexmorley** [flatironinstitute/spikeforest_old#38]
I'm intrigued to see how wave_clus compares as I think it is used by *a lot* of people. I'm going to try to add it in a few weeks (unless any MATLAB-competent fold wants to do it before then).

**Comment by magland** [comment]
James has added this: https://github.com/flatironinstitute/spikeforest/tree/master/spikeforest/spikesorters/waveclus

Right now we are only applying it to monotrode recordings.

**Comment by alexmorley** [comment]
Ah awesome :)
