### ISSUE TITLE
Heuristics for clustered units 

### ISSUE THREAD

**Issue by jvoigts** [flatironinstitute/spikeforest_old#83]
I'd like to check what you all are thinking about adding a mechanism for, or repository of, heuristics to decide if a cluster returned by a spike sorter is of neural origin.

It seems that quite a few users of automated sorters use ad-hoc scripts, often in addition to manual curation, in order to mark and remove clusters that are clearly artifacts. For instance, by checking if the ISI distribution is sensible, and if the spike waveform looks neural etc.

As a 'off-label' use of these heuristics, one could also add classifications, such as regular vs. fast spiking cortical neurons etc. 

These heuristics are of course somewhat dependent on electrode type, brain region, and experimental setup, etc. but there should be enough commonalities to make sharing these heuristics useful. Also, it seems like a common framework like spikeforest (or spikeinterface) is the correct place to plug in such heuristics, to decouple them from specific sorters.

If you think this should go somewhere else, I'd also be interested to hear where, and what form such a repository could take.

**Comment by magland** [comment]
Thanks for the comment and interesting ideas. I think those would belong best inside spikeinterface and then they can be incorporated into spikeforest. See: https://github.com/SpikeInterface

**Comment by jvoigts** [comment]
Sounds good, I copied the issue over there: https://github.com/SpikeInterface/spiketoolkit/issues/283
